### ISSUE TITLE
Error during cog build/setup

### ISSUE THREAD

**Issue by key88sf** [daanelson/cog-blip-2#4]
Hi - I am running `cog build` on an AWS g5.xlarge gpu machine, and getting this error:
```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.pyenv/versions/3.8.18/lib/python3.8/site-packages/cog/command/openapi_schema.py", line 18, in <module>
    app = create_app(config, shutdown_event=None)
  File "/root/.pyenv/versions/3.8.18/lib/python3.8/site-packages/cog/server/http.py", line 72, in create_app
    predictor = load_predictor_from_ref(predictor_ref)
  File "/root/.pyenv/versions/3.8.18/lib/python3.8/site-packages/cog/predictor.py", line 172, in load_predictor_from_ref
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "predict.py", line 13, in <module>
    download_weights(url=WEIGHTS_URL,dest=WEIGHTS_CACHE_DIR)
  File "/src/download_utils.py", line 16, in download_weights
    raise e
  File "/src/download_utils.py", line 11, in download_weights
    output = subprocess.check_output(["pget", url, "/src/tmp.tar"])
  File "/root/.pyenv/versions/3.8.18/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/root/.pyenv/versions/3.8.18/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pget', 'https://weights.replicate.delivery/default/blip-2/weights.tar', '/src/tmp.tar']' died with <Signals.SIGKILL: 9>.

ⅹ Failed to get type signature: exit status 1
```

Trying again I get this:

```
Starting Docker image cog-blip-2-base and running setup()...
Downloading weights...
b''
ⅹ Timed out
```

Any idea what is going on? Seems like there is an issue with the weights file. Thank you for your help.

**Comment by key88sf** [comment]
Seems like Replicate fixed whatever that problem was -- weights are downloading now.
